SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;

USE SCHEMA DATAFEEDS;

SELECT * FROM GOOGLE_KEYWORDS LIMIT 100;

SELECT KEYWORD, YEAR, COUNT(KEYWORD) AS Units
FROM GOOGLE_KEYWORDS
GROUP BY KEYWORD, YEAR
ORDER BY Units DESC
LIMIT 1000;


DESCRIBE TABLE GOOGLE_KEYWORDS;

--c
SELECT COUNT(*)
FROM GOOGLE_KEYWORDS;

--d
SELECT DISTINCT DATE  
FROM GOOGLE_KEYWORDS
WHERE DATE = (SELECT MIN(DATE)
FROM GOOGLE_KEYWORDS);
SELECT DISTINCT DATE  
FROM GOOGLE_KEYWORDS
WHERE DATE = (SELECT MAX(DATE)
FROM GOOGLE_KEYWORDS);

--e Which are the 10 most popular keywords?

SELECT TOP 10 *
FROM GOOGLE_KEYWORDS;

SELECT KEYWORD, COUNT(KEYWORD) AS Number_keyword
FROM GOOGLE_KEYWORDS
GROUP BY KEYWORD
ORDER BY Number_keyword DESC
LIMIT 10;

--  f) How many unique keywords are there?

SELECT DISTINCT(KEYWORD)
FROM GOOGLE_KEYWORDS;

-- g) Check what type of platforms are used and how many users per platform

SELECT DISTINCT(PLATFORM), COUNT(PLATFORM) AS Units
FROM GOOGLE_KEYWORDS
GROUP BY PLATFORM;
--35046855 desktop

--h)

SELECT DISTINCT(KEYWORD), COUNT(KEYWORD) AS Number_keyword
FROM GOOGLE_KEYWORDS
WHERE COUNTRY = 752
GROUP BY KEYWORD
ORDER BY Number_keyword DESC
LIMIT 20;

--i)
SELECT COUNTRY, COUNT(KEYWORD) AS Number_of_searches
FROM GOOGLE_KEYWORDS
WHERE KEYWORD IN ('spotify', 'Spotify')
GROUP BY COUNTRY
ORDER BY Number_of_searches DESC
LIMIT 10;

--j)

SELECT DISTINCT(KEYWORD), COUNT(KEYWORD) AS Numbers
FROM GOOGLE_KEYWORDS
WHERE COUNTRY = 804
GROUP BY KEYWORD
ORDER BY Numbers DESC
LIMIT 10;

-- COST 1,38 cent per queries

SELECT * 
FROM GOOGLE_KEYWORDS
LIMIT 10;

SELECT SITE, COUNT(SITE) AS Numbers
FROM GOOGLE_KEYWORDS
GROUP BY SITE
ORDER BY Numbers DESC
LIMIT 100;